version: 2

jobs:
  build:
    working_directory: ~/circleci_test
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run .
#workflows:
#  version: 2
#
#  test:
#    jobs:
#      - pep8
#      - py27
#      - py36
#      - py37