name: Python application
on: [push]
jobs:
  local_test:
    runs-on: self-hosted
    steps:
      - run: python -V
#        echo This job does specify a container.
#        echo It runs in the container instead of the VM.
#        name: Run in container
#  test_local:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.
#         architecture: 'x64' # Optional - x64 or x86, defaults to x64

#     - name: Cache pip
#       uses: actions/cache@v1
#       with:
#         path: ~/.cache/pip # This path is specific to Ubuntu
#         # Look to see if there is a cache hit for the corresponding requirements file
#         key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#         restore-keys: |
#           ${{ runner.os }}-pip-
#           ${{ runner.os }}-

#     - name: Install dependencies
#       run: pip install -r requirements.txt

#    - name: Display Python version
#      run: python -c "import sys; print(sys.version)"

#     - name: Test with pytest
#       run: pytest
