name: Python application
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
